### obtener todas las reservas
GET http://localhost:3000/api/reserva

### crear una nueva reserva
POST http://localhost:3000/api/reserva
Content-Type: application/json

{
    "fechaReserva": "2024-11-20",
    "horaInicio": "20:00hs",
    "horaFin": "21:00hs",
    "totalReserva": 45000,
    "idCliente": 13,
    "idCancha": 9,
    "idEmpleado": 5
}

### ID
@id = 1

### GET one reserva
http://localhost:3000/api/reserva/{{id}}

### PUT update a reserva
PUT http://localhost:3000/api/reserva/{{id}}
Content-Type: application/json

{
  "horaInicio": "19:00hs",
    "horaFin": "20:00hs"
}

### DELETE a reserva - cancelar reserva
@idToDelete = 14
DELETE http://localhost:3000/api/reserva/{{idToDelete}}