### GET ALL
GET http://localhost:3000/api/reserva_articulo/classes

### POST
# @name createReservaArticuloClass
POST http://localhost:3000/api/reserva_articulo/classes
Content-Type: application/json

{

}

### ID
@id = 1

### GET ONE
GET http://localhost:3000/api/reserva_articulo/classes/{{id}}

### PUT
PUT  http://localhost:3000/api/reserva_articulo/classes/{{id}}
Content-Type: application/json

{
   
}

### DELETE
@idToDelete = 1
DELETE http://localhost:3000/api/reserva_articulo/classes/{{idToDelete}}