### GET ALL
GET http://localhost:3000/api/cancha/classes

### POST
# @name createCanchaClass
POST http://localhost:3000/api/cancha/classes
Content-Type: application/json

{
    "precioHora": 20000,
    "tipoCancha": "futbol 5"
}


### ID
@id = 3

### GET ONE
GET http://localhost:3000/api/cancha/classes/{{id}}

### PUT
PUT  http://localhost:3000/api/cancha/classes/{{id}}
Content-Type: application/json

{
    "precioHora": 25000
}

### DELETE
@idToDelete = 9
DELETE http://localhost:3000/api/cancha/classes/{{idToDelete}}