### obtener todas las personas
GET http://localhost:3000/api/persona

### crear una nueva persona
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "name": "Octavio",
    "lastname": "Sesana",
    "dni": 43644808,
    "phone": 3463440,
    "email": "octasesana@gmail.com",
    "password": "hola"
}

### Login de persona
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "octasesana@gmail.com",
  "password": "hola"
}


### ID
@email = leomessi2022@gmail.com

### GET one persona
http://localhost:3000/api/persona/{{email}}


### PUT update a persona
PUT http://localhost:3000/api/persona/{{email}}
Content-Type: application/json

{
  "email": "leomessi@gmail.com",
  "phone": 123456
}

### DELETE a persona
@idToDelete = 4
DELETE http://localhost:3000/api/persona/{{idToDelete}}