### obtener todas las personas
GET http://localhost:3000/api/persona

### crear una nueva persona
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "name": "Martina",
    "lastname": "Vivas",
    "dni": 3345,
    "phone": 1234,
    "email": "octasesana@gmail.com"
    //"personaClass": 12
}

### ID
@id = 17

### GET one persona
http://localhost:3000/api/persona/{{id}}


### PUT update a persona
PUT http://localhost:3000/api/persona/{{id}}
Content-Type: application/json

{
  "name": "Martita"
}

### DELETE a persona
@idToDelete = 22
DELETE http://localhost:3000/api/persona/{{idToDelete}}