### GET ALL
GET http://localhost:3000/api/persona/classes

### POST
# @name createPersonaClass
POST http://localhost:3000/api/persona/classes
Content-Type: application/json

{
    "email": "eltinche@gmail.com",
    "phone": "458"
}

### ID
@id = 10

### GET ONE
GET http://localhost:3000/api/persona/classes/{{id}}

### PUT
PUT  http://localhost:3000/api/persona/classes/{{id}}
Content-Type: application/json

{
    "email": "martaxd@gmail.com"
}

### DELETE
@idToDelete = 13
DELETE http://localhost:3000/api/persona/classes/{{idToDelete}}