### obtener todas las personas
GET http://localhost:3000/api/persona

### crear una nueva persona
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "name": "Delfina",
    "lastname": "Tartaglini",
    "dni": 6745,
    "phone": 1756234,
    "email": "delfittt@gmail.com",
    "password": "hola"
    //"personaClass": 12
}

### ID
@email = leomessi@gmail.com

### GET one persona
http://localhost:3000/api/persona/{{email}}


### PUT update a persona
PUT http://localhost:3000/api/persona/{{email}}
Content-Type: application/json

{
  "name": "Delfina"
}

### DELETE a persona
@idToDelete = 2
DELETE http://localhost:3000/api/persona/{{idToDelete}}