### GET ALL
GET http://localhost:3000/api/articulo/classes

### POST
# @name createArticuloClass
POST http://localhost:3000/api/articulo/classes
Content-Type: application/json

{
    "cantDisponible": 1,
    "estado": "Disponible"
}

### ID
@id = 8

### GET ONE
GET http://localhost:3000/api/articulo/classes/{{id}}

### PUT
PUT  http://localhost:3000/api/articulo/classes/{{id}}
Content-Type: application/json

{
    "estado": "Disponible"
}

### DELETE
@idToDelete = 1
DELETE http://localhost:3000/api/articulo/classes/{{idToDelete}}